inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - Rakefile

Layout/LineLength:
  Max: 120

Rails:
  Enabled: true

Naming/FileName:
  Exclude:
    - bin/scss-lint

Style/RescueModifier:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/RedundantFetchBlock:
  Exclude:
    - 'config/initializers/redis_pool.rb'

Style/OptionalBooleanParameter:
  Exclude:
    - 'app/view_models/navigation.rb'