AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/FileName:
  Exclude:
    - bin/scss-lint

Style/RescueModifier:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

AmbiguousOperator:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
