inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - Rakefile

Layout/LineLength:
  Max: 120

Rails:
  Enabled: true

Naming/FileName:
  Exclude:
    - bin/scss-lint

Style/RescueModifier:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/RedundantFetchBlock:
  Exclude:
    - 'config/initializers/redis_pool.rb'

Style/OptionalBooleanParameter:
  Exclude:
    - 'app/view_models/navigation.rb'

Lint/MissingSuper:
  Exclude:
    - 'app/decorators/cached_guide_decorator.rb'
    - 'app/decorators/location_decorator.rb'

Naming/VariableNumber:
  Exclude:
    - 'app/controllers/employer/bookings_controller.rb'
    - 'app/controllers/telephone_appointments_controller.rb'
    - 'features/pages/appointment_summary_generator.rb'
    - 'spec/controllers/concerns/breadcrumbs_controller_concern_spec.rb'
    - 'spec/lib/leave_pot_untouched_calculator_spec.rb'
    - 'spec/models/pension_summary/step_viewing_spec.rb'
    - 'spec/requests/locations_cache_sweeper_api_spec.rb'

Style/FormatStringToken:
  EnforcedStyle: template

Style/MutableConstant:
  Exclude:
    - 'app/domain/pension_summary.rb'
    - 'app/helpers/home_helper.rb'
    - 'app/lib/leave_pot_untouched_calculator.rb'

Style/HashLikeCase:
  Exclude:
    - 'features/step_definitions/appointment_summary_steps.rb'
    - 'features/step_definitions/location_steps.rb'


# Offense count: 1
Security/Open:
  Exclude:
    - 'app/lib/locations/reader.rb'