AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/FileName:
  Exclude:
    - bin/scss-lint

Style/RescueModifier:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

AmbiguousOperator:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
