name: "CI"
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      RAILS_ENV: test
      DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/pension_guidance_test'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
      - name: Install npm packages
        run: npm install
      - name: Install Prince
        run: |
          curl https://www.princexml.com/download/prince_16.2-1_ubuntu24.04_amd64.deb -O
          sudo apt install ./prince_16.2-1_ubuntu24.04_amd64.deb
      - name: Set up database schema
        run: 'bundle exec rake db:create db:migrate'
      - name: Run tests and lint
        run: bundle exec rake
